// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package poslovnabanka.proxies;

public class Banka
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bankaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PoslovnaBanka.Banka";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		naziv("naziv"),
		sifra("sifra"),
		SWIFTkod("SWIFTkod"),
		adresa("adresa"),
		kontaktTelefon("kontaktTelefon"),
		obracunskiRacun("obracunskiRacun"),
		BankaIzMesta("PoslovnaBanka.BankaIzMesta"),
		BankaDuznika("PoslovnaBanka.BankaDuznika"),
		BankaPoverioca("PoslovnaBanka.BankaPoverioca"),
		ObracunskiRacun_Banka("NarodnaBanka.ObracunskiRacun_Banka");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Banka(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Banka(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bankaMendixObject)
	{
		if (bankaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, bankaMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.bankaMendixObject = bankaMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Banka.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static poslovnabanka.proxies.Banka initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return poslovnabanka.proxies.Banka.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static poslovnabanka.proxies.Banka initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new poslovnabanka.proxies.Banka(context, mendixObject);
	}

	public static poslovnabanka.proxies.Banka load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return poslovnabanka.proxies.Banka.initialize(context, mendixObject);
	}

	public static java.util.List<poslovnabanka.proxies.Banka> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> poslovnabanka.proxies.Banka.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of naziv
	 */
	public final java.lang.String getnaziv()
	{
		return getnaziv(getContext());
	}

	/**
	 * @param context
	 * @return value of naziv
	 */
	public final java.lang.String getnaziv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.naziv.toString());
	}

	/**
	 * Set value of naziv
	 * @param naziv
	 */
	public final void setnaziv(java.lang.String naziv)
	{
		setnaziv(getContext(), naziv);
	}

	/**
	 * Set value of naziv
	 * @param context
	 * @param naziv
	 */
	public final void setnaziv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String naziv)
	{
		getMendixObject().setValue(context, MemberNames.naziv.toString(), naziv);
	}

	/**
	 * @return value of sifra
	 */
	public final java.lang.Long getsifra()
	{
		return getsifra(getContext());
	}

	/**
	 * @param context
	 * @return value of sifra
	 */
	public final java.lang.Long getsifra(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.sifra.toString());
	}

	/**
	 * Set value of sifra
	 * @param sifra
	 */
	public final void setsifra(java.lang.Long sifra)
	{
		setsifra(getContext(), sifra);
	}

	/**
	 * Set value of sifra
	 * @param context
	 * @param sifra
	 */
	public final void setsifra(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long sifra)
	{
		getMendixObject().setValue(context, MemberNames.sifra.toString(), sifra);
	}

	/**
	 * @return value of SWIFTkod
	 */
	public final java.lang.String getSWIFTkod()
	{
		return getSWIFTkod(getContext());
	}

	/**
	 * @param context
	 * @return value of SWIFTkod
	 */
	public final java.lang.String getSWIFTkod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SWIFTkod.toString());
	}

	/**
	 * Set value of SWIFTkod
	 * @param swiftkod
	 */
	public final void setSWIFTkod(java.lang.String swiftkod)
	{
		setSWIFTkod(getContext(), swiftkod);
	}

	/**
	 * Set value of SWIFTkod
	 * @param context
	 * @param swiftkod
	 */
	public final void setSWIFTkod(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String swiftkod)
	{
		getMendixObject().setValue(context, MemberNames.SWIFTkod.toString(), swiftkod);
	}

	/**
	 * @return value of adresa
	 */
	public final java.lang.String getadresa()
	{
		return getadresa(getContext());
	}

	/**
	 * @param context
	 * @return value of adresa
	 */
	public final java.lang.String getadresa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.adresa.toString());
	}

	/**
	 * Set value of adresa
	 * @param adresa
	 */
	public final void setadresa(java.lang.String adresa)
	{
		setadresa(getContext(), adresa);
	}

	/**
	 * Set value of adresa
	 * @param context
	 * @param adresa
	 */
	public final void setadresa(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adresa)
	{
		getMendixObject().setValue(context, MemberNames.adresa.toString(), adresa);
	}

	/**
	 * @return value of kontaktTelefon
	 */
	public final java.lang.String getkontaktTelefon()
	{
		return getkontaktTelefon(getContext());
	}

	/**
	 * @param context
	 * @return value of kontaktTelefon
	 */
	public final java.lang.String getkontaktTelefon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.kontaktTelefon.toString());
	}

	/**
	 * Set value of kontaktTelefon
	 * @param kontakttelefon
	 */
	public final void setkontaktTelefon(java.lang.String kontakttelefon)
	{
		setkontaktTelefon(getContext(), kontakttelefon);
	}

	/**
	 * Set value of kontaktTelefon
	 * @param context
	 * @param kontakttelefon
	 */
	public final void setkontaktTelefon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kontakttelefon)
	{
		getMendixObject().setValue(context, MemberNames.kontaktTelefon.toString(), kontakttelefon);
	}

	/**
	 * @return value of obracunskiRacun
	 */
	public final java.lang.String getobracunskiRacun()
	{
		return getobracunskiRacun(getContext());
	}

	/**
	 * @param context
	 * @return value of obracunskiRacun
	 */
	public final java.lang.String getobracunskiRacun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.obracunskiRacun.toString());
	}

	/**
	 * Set value of obracunskiRacun
	 * @param obracunskiracun
	 */
	public final void setobracunskiRacun(java.lang.String obracunskiracun)
	{
		setobracunskiRacun(getContext(), obracunskiracun);
	}

	/**
	 * Set value of obracunskiRacun
	 * @param context
	 * @param obracunskiracun
	 */
	public final void setobracunskiRacun(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String obracunskiracun)
	{
		getMendixObject().setValue(context, MemberNames.obracunskiRacun.toString(), obracunskiracun);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BankaIzMesta
	 */
	public final poslovnabanka.proxies.Mesto getBankaIzMesta() throws com.mendix.core.CoreException
	{
		return getBankaIzMesta(getContext());
	}

	/**
	 * @param context
	 * @return value of BankaIzMesta
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.Mesto getBankaIzMesta(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.Mesto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankaIzMesta.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.Mesto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BankaIzMesta
	 * @param bankaizmesta
	 */
	public final void setBankaIzMesta(poslovnabanka.proxies.Mesto bankaizmesta)
	{
		setBankaIzMesta(getContext(), bankaizmesta);
	}

	/**
	 * Set value of BankaIzMesta
	 * @param context
	 * @param bankaizmesta
	 */
	public final void setBankaIzMesta(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.Mesto bankaizmesta)
	{
		if (bankaizmesta == null) {
			getMendixObject().setValue(context, MemberNames.BankaIzMesta.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BankaIzMesta.toString(), bankaizmesta.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BankaDuznika
	 */
	public final poslovnabanka.proxies.PorukaPrenosa getBankaDuznika() throws com.mendix.core.CoreException
	{
		return getBankaDuznika(getContext());
	}

	/**
	 * @param context
	 * @return value of BankaDuznika
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.PorukaPrenosa getBankaDuznika(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.PorukaPrenosa result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankaDuznika.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.PorukaPrenosa.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BankaDuznika
	 * @param bankaduznika
	 */
	public final void setBankaDuznika(poslovnabanka.proxies.PorukaPrenosa bankaduznika)
	{
		setBankaDuznika(getContext(), bankaduznika);
	}

	/**
	 * Set value of BankaDuznika
	 * @param context
	 * @param bankaduznika
	 */
	public final void setBankaDuznika(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.PorukaPrenosa bankaduznika)
	{
		if (bankaduznika == null) {
			getMendixObject().setValue(context, MemberNames.BankaDuznika.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BankaDuznika.toString(), bankaduznika.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BankaPoverioca
	 */
	public final poslovnabanka.proxies.PorukaPrenosa getBankaPoverioca() throws com.mendix.core.CoreException
	{
		return getBankaPoverioca(getContext());
	}

	/**
	 * @param context
	 * @return value of BankaPoverioca
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.PorukaPrenosa getBankaPoverioca(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.PorukaPrenosa result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankaPoverioca.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.PorukaPrenosa.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BankaPoverioca
	 * @param bankapoverioca
	 */
	public final void setBankaPoverioca(poslovnabanka.proxies.PorukaPrenosa bankapoverioca)
	{
		setBankaPoverioca(getContext(), bankapoverioca);
	}

	/**
	 * Set value of BankaPoverioca
	 * @param context
	 * @param bankapoverioca
	 */
	public final void setBankaPoverioca(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.PorukaPrenosa bankapoverioca)
	{
		if (bankapoverioca == null) {
			getMendixObject().setValue(context, MemberNames.BankaPoverioca.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BankaPoverioca.toString(), bankapoverioca.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ObracunskiRacun_Banka
	 */
	public final narodnabanka.proxies.ObracunskiRacun getObracunskiRacun_Banka() throws com.mendix.core.CoreException
	{
		return getObracunskiRacun_Banka(getContext());
	}

	/**
	 * @param context
	 * @return value of ObracunskiRacun_Banka
	 * @throws com.mendix.core.CoreException
	 */
	public final narodnabanka.proxies.ObracunskiRacun getObracunskiRacun_Banka(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		narodnabanka.proxies.ObracunskiRacun result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ObracunskiRacun_Banka.toString());
		if (identifier != null) {
			result = narodnabanka.proxies.ObracunskiRacun.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ObracunskiRacun_Banka
	 * @param obracunskiracun_banka
	 */
	public final void setObracunskiRacun_Banka(narodnabanka.proxies.ObracunskiRacun obracunskiracun_banka)
	{
		setObracunskiRacun_Banka(getContext(), obracunskiracun_banka);
	}

	/**
	 * Set value of ObracunskiRacun_Banka
	 * @param context
	 * @param obracunskiracun_banka
	 */
	public final void setObracunskiRacun_Banka(com.mendix.systemwideinterfaces.core.IContext context, narodnabanka.proxies.ObracunskiRacun obracunskiracun_banka)
	{
		if (obracunskiracun_banka == null) {
			getMendixObject().setValue(context, MemberNames.ObracunskiRacun_Banka.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ObracunskiRacun_Banka.toString(), obracunskiracun_banka.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bankaMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final poslovnabanka.proxies.Banka that = (poslovnabanka.proxies.Banka) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
