// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package poslovnabanka.proxies;

public class DnevnoStanje
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dnevnoStanjeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PoslovnaBanka.DnevnoStanje";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		datumPrometa("datumPrometa"),
		prethodnoStanje("prethodnoStanje"),
		promenaNaTeret("promenaNaTeret"),
		promenaUKorist("promenaUKorist"),
		novoStanje("novoStanje"),
		DnevnoStanje_Racun("PoslovnaBanka.DnevnoStanje_Racun"),
		NalogDnevnoStanje("PoslovnaBanka.NalogDnevnoStanje");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DnevnoStanje(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DnevnoStanje(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dnevnoStanjeMendixObject)
	{
		if (dnevnoStanjeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dnevnoStanjeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dnevnoStanjeMendixObject = dnevnoStanjeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DnevnoStanje.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static poslovnabanka.proxies.DnevnoStanje initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return poslovnabanka.proxies.DnevnoStanje.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static poslovnabanka.proxies.DnevnoStanje initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new poslovnabanka.proxies.DnevnoStanje(context, mendixObject);
	}

	public static poslovnabanka.proxies.DnevnoStanje load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return poslovnabanka.proxies.DnevnoStanje.initialize(context, mendixObject);
	}

	public static java.util.List<poslovnabanka.proxies.DnevnoStanje> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> poslovnabanka.proxies.DnevnoStanje.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of datumPrometa
	 */
	public final java.util.Date getdatumPrometa()
	{
		return getdatumPrometa(getContext());
	}

	/**
	 * @param context
	 * @return value of datumPrometa
	 */
	public final java.util.Date getdatumPrometa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumPrometa.toString());
	}

	/**
	 * Set value of datumPrometa
	 * @param datumprometa
	 */
	public final void setdatumPrometa(java.util.Date datumprometa)
	{
		setdatumPrometa(getContext(), datumprometa);
	}

	/**
	 * Set value of datumPrometa
	 * @param context
	 * @param datumprometa
	 */
	public final void setdatumPrometa(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumprometa)
	{
		getMendixObject().setValue(context, MemberNames.datumPrometa.toString(), datumprometa);
	}

	/**
	 * @return value of prethodnoStanje
	 */
	public final java.math.BigDecimal getprethodnoStanje()
	{
		return getprethodnoStanje(getContext());
	}

	/**
	 * @param context
	 * @return value of prethodnoStanje
	 */
	public final java.math.BigDecimal getprethodnoStanje(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.prethodnoStanje.toString());
	}

	/**
	 * Set value of prethodnoStanje
	 * @param prethodnostanje
	 */
	public final void setprethodnoStanje(java.math.BigDecimal prethodnostanje)
	{
		setprethodnoStanje(getContext(), prethodnostanje);
	}

	/**
	 * Set value of prethodnoStanje
	 * @param context
	 * @param prethodnostanje
	 */
	public final void setprethodnoStanje(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal prethodnostanje)
	{
		getMendixObject().setValue(context, MemberNames.prethodnoStanje.toString(), prethodnostanje);
	}

	/**
	 * @return value of promenaNaTeret
	 */
	public final java.math.BigDecimal getpromenaNaTeret()
	{
		return getpromenaNaTeret(getContext());
	}

	/**
	 * @param context
	 * @return value of promenaNaTeret
	 */
	public final java.math.BigDecimal getpromenaNaTeret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.promenaNaTeret.toString());
	}

	/**
	 * Set value of promenaNaTeret
	 * @param promenanateret
	 */
	public final void setpromenaNaTeret(java.math.BigDecimal promenanateret)
	{
		setpromenaNaTeret(getContext(), promenanateret);
	}

	/**
	 * Set value of promenaNaTeret
	 * @param context
	 * @param promenanateret
	 */
	public final void setpromenaNaTeret(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal promenanateret)
	{
		getMendixObject().setValue(context, MemberNames.promenaNaTeret.toString(), promenanateret);
	}

	/**
	 * @return value of promenaUKorist
	 */
	public final java.math.BigDecimal getpromenaUKorist()
	{
		return getpromenaUKorist(getContext());
	}

	/**
	 * @param context
	 * @return value of promenaUKorist
	 */
	public final java.math.BigDecimal getpromenaUKorist(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.promenaUKorist.toString());
	}

	/**
	 * Set value of promenaUKorist
	 * @param promenaukorist
	 */
	public final void setpromenaUKorist(java.math.BigDecimal promenaukorist)
	{
		setpromenaUKorist(getContext(), promenaukorist);
	}

	/**
	 * Set value of promenaUKorist
	 * @param context
	 * @param promenaukorist
	 */
	public final void setpromenaUKorist(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal promenaukorist)
	{
		getMendixObject().setValue(context, MemberNames.promenaUKorist.toString(), promenaukorist);
	}

	/**
	 * @return value of novoStanje
	 */
	public final java.math.BigDecimal getnovoStanje()
	{
		return getnovoStanje(getContext());
	}

	/**
	 * @param context
	 * @return value of novoStanje
	 */
	public final java.math.BigDecimal getnovoStanje(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.novoStanje.toString());
	}

	/**
	 * Set value of novoStanje
	 * @param novostanje
	 */
	public final void setnovoStanje(java.math.BigDecimal novostanje)
	{
		setnovoStanje(getContext(), novostanje);
	}

	/**
	 * Set value of novoStanje
	 * @param context
	 * @param novostanje
	 */
	public final void setnovoStanje(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal novostanje)
	{
		getMendixObject().setValue(context, MemberNames.novoStanje.toString(), novostanje);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DnevnoStanje_Racun
	 */
	public final poslovnabanka.proxies.Racun getDnevnoStanje_Racun() throws com.mendix.core.CoreException
	{
		return getDnevnoStanje_Racun(getContext());
	}

	/**
	 * @param context
	 * @return value of DnevnoStanje_Racun
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.Racun getDnevnoStanje_Racun(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.Racun result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DnevnoStanje_Racun.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.Racun.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DnevnoStanje_Racun
	 * @param dnevnostanje_racun
	 */
	public final void setDnevnoStanje_Racun(poslovnabanka.proxies.Racun dnevnostanje_racun)
	{
		setDnevnoStanje_Racun(getContext(), dnevnostanje_racun);
	}

	/**
	 * Set value of DnevnoStanje_Racun
	 * @param context
	 * @param dnevnostanje_racun
	 */
	public final void setDnevnoStanje_Racun(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.Racun dnevnostanje_racun)
	{
		if (dnevnostanje_racun == null) {
			getMendixObject().setValue(context, MemberNames.DnevnoStanje_Racun.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DnevnoStanje_Racun.toString(), dnevnostanje_racun.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of NalogDnevnoStanje
	 */
	public final poslovnabanka.proxies.NalogZaPlacanje getNalogDnevnoStanje() throws com.mendix.core.CoreException
	{
		return getNalogDnevnoStanje(getContext());
	}

	/**
	 * @param context
	 * @return value of NalogDnevnoStanje
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.NalogZaPlacanje getNalogDnevnoStanje(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.NalogZaPlacanje result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NalogDnevnoStanje.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.NalogZaPlacanje.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of NalogDnevnoStanje
	 * @param nalogdnevnostanje
	 */
	public final void setNalogDnevnoStanje(poslovnabanka.proxies.NalogZaPlacanje nalogdnevnostanje)
	{
		setNalogDnevnoStanje(getContext(), nalogdnevnostanje);
	}

	/**
	 * Set value of NalogDnevnoStanje
	 * @param context
	 * @param nalogdnevnostanje
	 */
	public final void setNalogDnevnoStanje(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.NalogZaPlacanje nalogdnevnostanje)
	{
		if (nalogdnevnostanje == null) {
			getMendixObject().setValue(context, MemberNames.NalogDnevnoStanje.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.NalogDnevnoStanje.toString(), nalogdnevnostanje.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dnevnoStanjeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final poslovnabanka.proxies.DnevnoStanje that = (poslovnabanka.proxies.DnevnoStanje) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
