// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package poslovnabanka.proxies;

public class Klijent
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject klijentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PoslovnaBanka.Klijent";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Ime("Ime"),
		prezime("prezime"),
		IdBroj("IdBroj"),
		adresa("adresa"),
		kontaktTelefon("kontaktTelefon"),
		email("email"),
		PIB("PIB"),
		MIB("MIB"),
		naziv("naziv"),
		vrsta("vrsta"),
		KlijentIzMesta("PoslovnaBanka.KlijentIzMesta"),
		Klijent_SifrarnikDelatnosti("PoslovnaBanka.Klijent_SifrarnikDelatnosti");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Klijent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Klijent(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject klijentMendixObject)
	{
		if (klijentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, klijentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.klijentMendixObject = klijentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Klijent.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static poslovnabanka.proxies.Klijent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return poslovnabanka.proxies.Klijent.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static poslovnabanka.proxies.Klijent initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new poslovnabanka.proxies.Klijent(context, mendixObject);
	}

	public static poslovnabanka.proxies.Klijent load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return poslovnabanka.proxies.Klijent.initialize(context, mendixObject);
	}

	public static java.util.List<poslovnabanka.proxies.Klijent> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> poslovnabanka.proxies.Klijent.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Ime
	 */
	public final java.lang.String getIme()
	{
		return getIme(getContext());
	}

	/**
	 * @param context
	 * @return value of Ime
	 */
	public final java.lang.String getIme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ime.toString());
	}

	/**
	 * Set value of Ime
	 * @param ime
	 */
	public final void setIme(java.lang.String ime)
	{
		setIme(getContext(), ime);
	}

	/**
	 * Set value of Ime
	 * @param context
	 * @param ime
	 */
	public final void setIme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ime)
	{
		getMendixObject().setValue(context, MemberNames.Ime.toString(), ime);
	}

	/**
	 * @return value of prezime
	 */
	public final java.lang.String getprezime()
	{
		return getprezime(getContext());
	}

	/**
	 * @param context
	 * @return value of prezime
	 */
	public final java.lang.String getprezime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.prezime.toString());
	}

	/**
	 * Set value of prezime
	 * @param prezime
	 */
	public final void setprezime(java.lang.String prezime)
	{
		setprezime(getContext(), prezime);
	}

	/**
	 * Set value of prezime
	 * @param context
	 * @param prezime
	 */
	public final void setprezime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prezime)
	{
		getMendixObject().setValue(context, MemberNames.prezime.toString(), prezime);
	}

	/**
	 * @return value of IdBroj
	 */
	public final java.lang.String getIdBroj()
	{
		return getIdBroj(getContext());
	}

	/**
	 * @param context
	 * @return value of IdBroj
	 */
	public final java.lang.String getIdBroj(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IdBroj.toString());
	}

	/**
	 * Set value of IdBroj
	 * @param idbroj
	 */
	public final void setIdBroj(java.lang.String idbroj)
	{
		setIdBroj(getContext(), idbroj);
	}

	/**
	 * Set value of IdBroj
	 * @param context
	 * @param idbroj
	 */
	public final void setIdBroj(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String idbroj)
	{
		getMendixObject().setValue(context, MemberNames.IdBroj.toString(), idbroj);
	}

	/**
	 * @return value of adresa
	 */
	public final java.lang.String getadresa()
	{
		return getadresa(getContext());
	}

	/**
	 * @param context
	 * @return value of adresa
	 */
	public final java.lang.String getadresa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.adresa.toString());
	}

	/**
	 * Set value of adresa
	 * @param adresa
	 */
	public final void setadresa(java.lang.String adresa)
	{
		setadresa(getContext(), adresa);
	}

	/**
	 * Set value of adresa
	 * @param context
	 * @param adresa
	 */
	public final void setadresa(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adresa)
	{
		getMendixObject().setValue(context, MemberNames.adresa.toString(), adresa);
	}

	/**
	 * @return value of kontaktTelefon
	 */
	public final java.lang.String getkontaktTelefon()
	{
		return getkontaktTelefon(getContext());
	}

	/**
	 * @param context
	 * @return value of kontaktTelefon
	 */
	public final java.lang.String getkontaktTelefon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.kontaktTelefon.toString());
	}

	/**
	 * Set value of kontaktTelefon
	 * @param kontakttelefon
	 */
	public final void setkontaktTelefon(java.lang.String kontakttelefon)
	{
		setkontaktTelefon(getContext(), kontakttelefon);
	}

	/**
	 * Set value of kontaktTelefon
	 * @param context
	 * @param kontakttelefon
	 */
	public final void setkontaktTelefon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kontakttelefon)
	{
		getMendixObject().setValue(context, MemberNames.kontaktTelefon.toString(), kontakttelefon);
	}

	/**
	 * @return value of email
	 */
	public final java.lang.String getemail()
	{
		return getemail(getContext());
	}

	/**
	 * @param context
	 * @return value of email
	 */
	public final java.lang.String getemail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.email.toString());
	}

	/**
	 * Set value of email
	 * @param email
	 */
	public final void setemail(java.lang.String email)
	{
		setemail(getContext(), email);
	}

	/**
	 * Set value of email
	 * @param context
	 * @param email
	 */
	public final void setemail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.email.toString(), email);
	}

	/**
	 * @return value of PIB
	 */
	public final java.lang.String getPIB()
	{
		return getPIB(getContext());
	}

	/**
	 * @param context
	 * @return value of PIB
	 */
	public final java.lang.String getPIB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PIB.toString());
	}

	/**
	 * Set value of PIB
	 * @param pib
	 */
	public final void setPIB(java.lang.String pib)
	{
		setPIB(getContext(), pib);
	}

	/**
	 * Set value of PIB
	 * @param context
	 * @param pib
	 */
	public final void setPIB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pib)
	{
		getMendixObject().setValue(context, MemberNames.PIB.toString(), pib);
	}

	/**
	 * @return value of MIB
	 */
	public final java.lang.String getMIB()
	{
		return getMIB(getContext());
	}

	/**
	 * @param context
	 * @return value of MIB
	 */
	public final java.lang.String getMIB(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MIB.toString());
	}

	/**
	 * Set value of MIB
	 * @param mib
	 */
	public final void setMIB(java.lang.String mib)
	{
		setMIB(getContext(), mib);
	}

	/**
	 * Set value of MIB
	 * @param context
	 * @param mib
	 */
	public final void setMIB(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mib)
	{
		getMendixObject().setValue(context, MemberNames.MIB.toString(), mib);
	}

	/**
	 * @return value of naziv
	 */
	public final java.lang.String getnaziv()
	{
		return getnaziv(getContext());
	}

	/**
	 * @param context
	 * @return value of naziv
	 */
	public final java.lang.String getnaziv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.naziv.toString());
	}

	/**
	 * Set value of naziv
	 * @param naziv
	 */
	public final void setnaziv(java.lang.String naziv)
	{
		setnaziv(getContext(), naziv);
	}

	/**
	 * Set value of naziv
	 * @param context
	 * @param naziv
	 */
	public final void setnaziv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String naziv)
	{
		getMendixObject().setValue(context, MemberNames.naziv.toString(), naziv);
	}

	/**
	 * Set value of vrsta
	 * @param vrsta
	 */
	public final poslovnabanka.proxies.vrstaKlijenta getvrsta()
	{
		return getvrsta(getContext());
	}

	/**
	 * @param context
	 * @return value of vrsta
	 */
	public final poslovnabanka.proxies.vrstaKlijenta getvrsta(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.vrsta.toString());
		if (obj == null) {
			return null;
		}
		return poslovnabanka.proxies.vrstaKlijenta.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of vrsta
	 * @param vrsta
	 */
	public final void setvrsta(poslovnabanka.proxies.vrstaKlijenta vrsta)
	{
		setvrsta(getContext(), vrsta);
	}

	/**
	 * Set value of vrsta
	 * @param context
	 * @param vrsta
	 */
	public final void setvrsta(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.vrstaKlijenta vrsta)
	{
		if (vrsta != null) {
			getMendixObject().setValue(context, MemberNames.vrsta.toString(), vrsta.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.vrsta.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of KlijentIzMesta
	 */
	public final poslovnabanka.proxies.Mesto getKlijentIzMesta() throws com.mendix.core.CoreException
	{
		return getKlijentIzMesta(getContext());
	}

	/**
	 * @param context
	 * @return value of KlijentIzMesta
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.Mesto getKlijentIzMesta(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.Mesto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.KlijentIzMesta.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.Mesto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of KlijentIzMesta
	 * @param klijentizmesta
	 */
	public final void setKlijentIzMesta(poslovnabanka.proxies.Mesto klijentizmesta)
	{
		setKlijentIzMesta(getContext(), klijentizmesta);
	}

	/**
	 * Set value of KlijentIzMesta
	 * @param context
	 * @param klijentizmesta
	 */
	public final void setKlijentIzMesta(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.Mesto klijentizmesta)
	{
		if (klijentizmesta == null) {
			getMendixObject().setValue(context, MemberNames.KlijentIzMesta.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.KlijentIzMesta.toString(), klijentizmesta.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Klijent_SifrarnikDelatnosti
	 */
	public final poslovnabanka.proxies.SifrarnikDelatnosti getKlijent_SifrarnikDelatnosti() throws com.mendix.core.CoreException
	{
		return getKlijent_SifrarnikDelatnosti(getContext());
	}

	/**
	 * @param context
	 * @return value of Klijent_SifrarnikDelatnosti
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.SifrarnikDelatnosti getKlijent_SifrarnikDelatnosti(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.SifrarnikDelatnosti result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Klijent_SifrarnikDelatnosti.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.SifrarnikDelatnosti.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Klijent_SifrarnikDelatnosti
	 * @param klijent_sifrarnikdelatnosti
	 */
	public final void setKlijent_SifrarnikDelatnosti(poslovnabanka.proxies.SifrarnikDelatnosti klijent_sifrarnikdelatnosti)
	{
		setKlijent_SifrarnikDelatnosti(getContext(), klijent_sifrarnikdelatnosti);
	}

	/**
	 * Set value of Klijent_SifrarnikDelatnosti
	 * @param context
	 * @param klijent_sifrarnikdelatnosti
	 */
	public final void setKlijent_SifrarnikDelatnosti(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.SifrarnikDelatnosti klijent_sifrarnikdelatnosti)
	{
		if (klijent_sifrarnikdelatnosti == null) {
			getMendixObject().setValue(context, MemberNames.Klijent_SifrarnikDelatnosti.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Klijent_SifrarnikDelatnosti.toString(), klijent_sifrarnikdelatnosti.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return klijentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final poslovnabanka.proxies.Klijent that = (poslovnabanka.proxies.Klijent) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
