// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package poslovnabanka.proxies;

public class Racun
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject racunMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PoslovnaBanka.Racun";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		brojRacuna("brojRacuna"),
		datumOtvaranja("datumOtvaranja"),
		aktivan("aktivan"),
		datumZatvaranja("datumZatvaranja"),
		saldo("saldo"),
		prenetoNaRacun("prenetoNaRacun"),
		BankovniRacun("PoslovnaBanka.BankovniRacun"),
		Racun_Klijent("PoslovnaBanka.Racun_Klijent");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Racun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Racun(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject racunMendixObject)
	{
		if (racunMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, racunMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.racunMendixObject = racunMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Racun.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static poslovnabanka.proxies.Racun initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return poslovnabanka.proxies.Racun.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static poslovnabanka.proxies.Racun initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new poslovnabanka.proxies.Racun(context, mendixObject);
	}

	public static poslovnabanka.proxies.Racun load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return poslovnabanka.proxies.Racun.initialize(context, mendixObject);
	}

	public static java.util.List<poslovnabanka.proxies.Racun> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> poslovnabanka.proxies.Racun.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of brojRacuna
	 */
	public final java.lang.String getbrojRacuna()
	{
		return getbrojRacuna(getContext());
	}

	/**
	 * @param context
	 * @return value of brojRacuna
	 */
	public final java.lang.String getbrojRacuna(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.brojRacuna.toString());
	}

	/**
	 * Set value of brojRacuna
	 * @param brojracuna
	 */
	public final void setbrojRacuna(java.lang.String brojracuna)
	{
		setbrojRacuna(getContext(), brojracuna);
	}

	/**
	 * Set value of brojRacuna
	 * @param context
	 * @param brojracuna
	 */
	public final void setbrojRacuna(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String brojracuna)
	{
		getMendixObject().setValue(context, MemberNames.brojRacuna.toString(), brojracuna);
	}

	/**
	 * @return value of datumOtvaranja
	 */
	public final java.util.Date getdatumOtvaranja()
	{
		return getdatumOtvaranja(getContext());
	}

	/**
	 * @param context
	 * @return value of datumOtvaranja
	 */
	public final java.util.Date getdatumOtvaranja(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumOtvaranja.toString());
	}

	/**
	 * Set value of datumOtvaranja
	 * @param datumotvaranja
	 */
	public final void setdatumOtvaranja(java.util.Date datumotvaranja)
	{
		setdatumOtvaranja(getContext(), datumotvaranja);
	}

	/**
	 * Set value of datumOtvaranja
	 * @param context
	 * @param datumotvaranja
	 */
	public final void setdatumOtvaranja(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumotvaranja)
	{
		getMendixObject().setValue(context, MemberNames.datumOtvaranja.toString(), datumotvaranja);
	}

	/**
	 * @return value of aktivan
	 */
	public final java.lang.Boolean getaktivan()
	{
		return getaktivan(getContext());
	}

	/**
	 * @param context
	 * @return value of aktivan
	 */
	public final java.lang.Boolean getaktivan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.aktivan.toString());
	}

	/**
	 * Set value of aktivan
	 * @param aktivan
	 */
	public final void setaktivan(java.lang.Boolean aktivan)
	{
		setaktivan(getContext(), aktivan);
	}

	/**
	 * Set value of aktivan
	 * @param context
	 * @param aktivan
	 */
	public final void setaktivan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean aktivan)
	{
		getMendixObject().setValue(context, MemberNames.aktivan.toString(), aktivan);
	}

	/**
	 * @return value of datumZatvaranja
	 */
	public final java.util.Date getdatumZatvaranja()
	{
		return getdatumZatvaranja(getContext());
	}

	/**
	 * @param context
	 * @return value of datumZatvaranja
	 */
	public final java.util.Date getdatumZatvaranja(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.datumZatvaranja.toString());
	}

	/**
	 * Set value of datumZatvaranja
	 * @param datumzatvaranja
	 */
	public final void setdatumZatvaranja(java.util.Date datumzatvaranja)
	{
		setdatumZatvaranja(getContext(), datumzatvaranja);
	}

	/**
	 * Set value of datumZatvaranja
	 * @param context
	 * @param datumzatvaranja
	 */
	public final void setdatumZatvaranja(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datumzatvaranja)
	{
		getMendixObject().setValue(context, MemberNames.datumZatvaranja.toString(), datumzatvaranja);
	}

	/**
	 * @return value of saldo
	 */
	public final java.math.BigDecimal getsaldo()
	{
		return getsaldo(getContext());
	}

	/**
	 * @param context
	 * @return value of saldo
	 */
	public final java.math.BigDecimal getsaldo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.saldo.toString());
	}

	/**
	 * Set value of saldo
	 * @param saldo
	 */
	public final void setsaldo(java.math.BigDecimal saldo)
	{
		setsaldo(getContext(), saldo);
	}

	/**
	 * Set value of saldo
	 * @param context
	 * @param saldo
	 */
	public final void setsaldo(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal saldo)
	{
		getMendixObject().setValue(context, MemberNames.saldo.toString(), saldo);
	}

	/**
	 * @return value of prenetoNaRacun
	 */
	public final java.lang.String getprenetoNaRacun()
	{
		return getprenetoNaRacun(getContext());
	}

	/**
	 * @param context
	 * @return value of prenetoNaRacun
	 */
	public final java.lang.String getprenetoNaRacun(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.prenetoNaRacun.toString());
	}

	/**
	 * Set value of prenetoNaRacun
	 * @param prenetonaracun
	 */
	public final void setprenetoNaRacun(java.lang.String prenetonaracun)
	{
		setprenetoNaRacun(getContext(), prenetonaracun);
	}

	/**
	 * Set value of prenetoNaRacun
	 * @param context
	 * @param prenetonaracun
	 */
	public final void setprenetoNaRacun(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String prenetonaracun)
	{
		getMendixObject().setValue(context, MemberNames.prenetoNaRacun.toString(), prenetonaracun);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BankovniRacun
	 */
	public final poslovnabanka.proxies.Banka getBankovniRacun() throws com.mendix.core.CoreException
	{
		return getBankovniRacun(getContext());
	}

	/**
	 * @param context
	 * @return value of BankovniRacun
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.Banka getBankovniRacun(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.Banka result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankovniRacun.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.Banka.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BankovniRacun
	 * @param bankovniracun
	 */
	public final void setBankovniRacun(poslovnabanka.proxies.Banka bankovniracun)
	{
		setBankovniRacun(getContext(), bankovniracun);
	}

	/**
	 * Set value of BankovniRacun
	 * @param context
	 * @param bankovniracun
	 */
	public final void setBankovniRacun(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.Banka bankovniracun)
	{
		if (bankovniracun == null) {
			getMendixObject().setValue(context, MemberNames.BankovniRacun.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BankovniRacun.toString(), bankovniracun.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Racun_Klijent
	 */
	public final poslovnabanka.proxies.Klijent getRacun_Klijent() throws com.mendix.core.CoreException
	{
		return getRacun_Klijent(getContext());
	}

	/**
	 * @param context
	 * @return value of Racun_Klijent
	 * @throws com.mendix.core.CoreException
	 */
	public final poslovnabanka.proxies.Klijent getRacun_Klijent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		poslovnabanka.proxies.Klijent result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Racun_Klijent.toString());
		if (identifier != null) {
			result = poslovnabanka.proxies.Klijent.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Racun_Klijent
	 * @param racun_klijent
	 */
	public final void setRacun_Klijent(poslovnabanka.proxies.Klijent racun_klijent)
	{
		setRacun_Klijent(getContext(), racun_klijent);
	}

	/**
	 * Set value of Racun_Klijent
	 * @param context
	 * @param racun_klijent
	 */
	public final void setRacun_Klijent(com.mendix.systemwideinterfaces.core.IContext context, poslovnabanka.proxies.Klijent racun_klijent)
	{
		if (racun_klijent == null) {
			getMendixObject().setValue(context, MemberNames.Racun_Klijent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Racun_Klijent.toString(), racun_klijent.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return racunMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final poslovnabanka.proxies.Racun that = (poslovnabanka.proxies.Racun) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
