// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package poslovnabanka.proxies;

public class SifrarnikDelatnosti
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sifrarnikDelatnostiMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "PoslovnaBanka.SifrarnikDelatnosti";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		naziv("naziv"),
		sifra("sifra");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SifrarnikDelatnosti(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SifrarnikDelatnosti(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sifrarnikDelatnostiMendixObject)
	{
		if (sifrarnikDelatnostiMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, sifrarnikDelatnostiMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sifrarnikDelatnostiMendixObject = sifrarnikDelatnostiMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SifrarnikDelatnosti.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static poslovnabanka.proxies.SifrarnikDelatnosti initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return poslovnabanka.proxies.SifrarnikDelatnosti.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static poslovnabanka.proxies.SifrarnikDelatnosti initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new poslovnabanka.proxies.SifrarnikDelatnosti(context, mendixObject);
	}

	public static poslovnabanka.proxies.SifrarnikDelatnosti load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return poslovnabanka.proxies.SifrarnikDelatnosti.initialize(context, mendixObject);
	}

	public static java.util.List<poslovnabanka.proxies.SifrarnikDelatnosti> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> poslovnabanka.proxies.SifrarnikDelatnosti.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of naziv
	 */
	public final java.lang.String getnaziv()
	{
		return getnaziv(getContext());
	}

	/**
	 * @param context
	 * @return value of naziv
	 */
	public final java.lang.String getnaziv(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.naziv.toString());
	}

	/**
	 * Set value of naziv
	 * @param naziv
	 */
	public final void setnaziv(java.lang.String naziv)
	{
		setnaziv(getContext(), naziv);
	}

	/**
	 * Set value of naziv
	 * @param context
	 * @param naziv
	 */
	public final void setnaziv(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String naziv)
	{
		getMendixObject().setValue(context, MemberNames.naziv.toString(), naziv);
	}

	/**
	 * @return value of sifra
	 */
	public final java.lang.String getsifra()
	{
		return getsifra(getContext());
	}

	/**
	 * @param context
	 * @return value of sifra
	 */
	public final java.lang.String getsifra(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.sifra.toString());
	}

	/**
	 * Set value of sifra
	 * @param sifra
	 */
	public final void setsifra(java.lang.String sifra)
	{
		setsifra(getContext(), sifra);
	}

	/**
	 * Set value of sifra
	 * @param context
	 * @param sifra
	 */
	public final void setsifra(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sifra)
	{
		getMendixObject().setValue(context, MemberNames.sifra.toString(), sifra);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sifrarnikDelatnostiMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final poslovnabanka.proxies.SifrarnikDelatnosti that = (poslovnabanka.proxies.SifrarnikDelatnosti) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
