// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package poslovnabanka.proxies;

public enum TipTransfera
{
	MT102(new java.lang.String[][] { new java.lang.String[] { "en_US", "102" } }),
	MT103(new java.lang.String[][] { new java.lang.String[] { "en_US", "103" } }),
	MT900(new java.lang.String[][] { new java.lang.String[] { "en_US", "900" } }),
	MT910(new java.lang.String[][] { new java.lang.String[] { "en_US", "910" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private TipTransfera(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
